# The two monsters {#why-hard}

## The little monster
The "little monster" comes from the primal parts of your brain which are concerned mostly about survival. It is motivated by dopamine and seeks to obtain as much as possible. In the wild, the behaviors that give us the most dopamine are the ones that best help us survive: eating and reproduction for example. When presented with unnatural, extreme sources of dopamine like USM or fast food, the little monster becomes obsessed with it. 

The little monster awakens when we go through dopamine withdrawal. Whenever you have free time, it feels like something is missing. You feel empty or restless - this is the little monster begging to be fed. If we give in to it, we are satisfied momentarily, but once we put down USM, dopamine levels start to decrease, starting the cycle over again.

If you abstain from USM for long enough, as your dopamine baseline returns to normal, the little monster will grow weaker and weaker before eventually dying out. The empty feeling disappears along with the other symptoms of withdrawals (low mood, lack of motivation and pleasure).

By itself, the little monster is a minor threat and if this was all there was to it, quitting would be easy.

## The big monster
Much more dangerous than the little monster is the big monster. Remember that all addicts are pulled in two directions, wanting to quit and wanting to use. The big monster is the part of you that wants to use. The little monster is a physical phenomenon, but the big monster is entirely mental. It is composed of two main parts: the (false) belief that USM gives you genuine pleasure or benefit, and the (irrational) fear of quitting USM. Once you understand these, it is easy to outsmart the big monster.

You may have heard of smokers who have quit for years, then pick up one cigarette and are hooked again. They defeated the little monster long ago, but failing to address the big monster, they eventually chose the pleasure of the cigarette - a pleasure that doesn't actually exist. Setting off the little monster, they fell back into the trap of addiction.

### The illusion of pleasure
I mentioned that USM users are fooled into thinking thinking that there is a genuine benefit to USM. This can be attributed to the dopamine release that USM causes. Remember that as you use more and more, dopamine desensitization occurs in the brain. You go through your life with lowered dopamine levels experiencing withdrawal most of the time and need to use USM to return to normal levels. Non-users don't get withdrawals, and the relief you get from using USM is what they feel all the time. In other words, you use USM to feel like someone who doesn't. Clearly you would have been better off if you hadn't become hooked in the first place. All you need to do is to stop using USM and your dopamine levels will return to normal.

You may be thinking "I know that already" but it probably hasn't truly sunk in. The problem is that the facts don't fit in with a user's experience. It is when you are using USM that you feel normal, and when you are not using, you suffer from withdrawal. When you feel low and empty, as soon as you pick up USM, your problem is cured. Your brain makes the obvious connection: using social media makes you feel better, not using it makes you feel bad, therefore it must be a good thing. This is the opposite of the truth - whenever you stop USM you feel bored, or empty, or depressed, but this is caused itself by using USM. Addicts think that their problems will be solved by the next hit of their drug, but in reality they were caused by the previous hit - an endless cycle until you break out.

Think of the absolute misery heroin addicts go through when they are deprived of their drug. Now think of the utter joy they get when they are finally able to stick a needle in their veins and end their cravings. Non-heroin addicts don't get that feeling of joy - it's caused by the little monster. We don't see it this way because the process of building tolerance to dopamine is slow and gradual. If the instant you used USM for the first time, you became hooked, becoming restless without it and needing to use it for hours to get through the day, it would quickly register that USM was the problem. In reality, withdrawals are slight as we begin to use, so we don't blame USM. By the time we realize we need to cut down, USM has cemented its place in our mind as something to reach for when we need a boost, to relax, or whenever we're bored and it doesn't occur to us the problems it fixes are the very ones it causes.

### Fear of quitting
By the same token, USM users are afraid to quit because they believe they are losing a crutch or genuine pleasure. They fear that the emptiness and boredom they feel when not using USM will be with them forever (not understanding dopamine desensitization). They despair at the thought of never getting the pleasure of using USM again (the illusion of pleasure). By now you should realize that both of these feelings are irrational. There is also the fear of withdrawals and cravings which I have yet to address.

#### Withdrawals and cravings {-}
We already went over the physical effects of dopamine withdrawal: low mood, boredom, a feeling of something being missing, etc. These symptoms are experienced by USM users every day when they put down their phone, and are easily bearable on their own even for extended periods of time. The trouble with withdrawals is not the physical aspects, but the little monster.

During attempts to quit, the little monster will periodically pop up and cry out to be satisfied - a craving. This tends to happen in situations where you normally use USM, such as if you've made a habit of using it in bed before sleep, but can happen at any time. Then the big monster kicks in. It tells you that you'll never be satisfied without USM. It tries to negotiate with you, telling you just this once won't hurt. It tells you that you picked the wrong time to quit, or maybe you can just cut down instead. It says the suffering you're going through trying to quit isn't it worth it and that it's better to be an addict. 

Once you realize the big monster is entirely irrational and no longer believe what it says, cravings lose their power. Humans have enough self-awareness to be able to ignore the little monster if they truly believe it's for the better. Without the support of the big monster, cravings are little more than intrusive thoughts - annoying, but ultimately they have no power over you. 

You may still pull out your phone to open USM as habit, or think without realizing "I should open (your USM app of choice)". Like a spinning wheel, these habits will continue for some time, but if you don't give in to them or mope about them the wheel will eventually grind to a halt.
