# Summary
For convenience, the key points of the book are summarized here. These are the core beliefs you will need to quit USM without pain and without falling back into the trap. Make sure you understand and agree with all of them. Go back to the relevant section and re-read if necessary.

1. Social media offers very little to no real benefit or pleasure. It only appears to because it relieves the negative withdrawal symptoms, but these symptoms are caused themselves by social media. Non-addicts don't suffer them.
2. USM users use social media in order to feed the little monster. The little monster awakens when going through dopamine withdrawal and is the source of cravings. If you stop using USM, the little monster eventually dies out.
3. Quitting is difficult because of the big monster: the illusion that USM gives you real benefit or pleasure and the fear of quitting. Both of these are irrational and once you see that, the big monster is defeated.
4. Once you have defeated the big monster, the little monster loses its power over you. Realize that there is no reason to want to use USM anymore. Then quitting is easy.
