# (APPENDIX) Appendix {-}
# Appendix A: The myth of losing control
Here I will try to present a comprehensive debunking of the idea that addicts don't have control over their use. In other words, that they are compelled to use or use involuntarily. Rather, addicts see using as the preferable option to quitting. For example, alcoholics wouldn't like to be alcoholics, but the idea of quitting makes them even more miserable than the idea of continuing to drink and as such they continue to abuse alcohol. This applies to ALL addictions, including USM.

This idea might seem ridiculous to some of you because this contradicts what we have been told for our whole lives. We hear that addiction is a chronic disease. Scare campaigns tell us that once you take drugs, you physically cannot stop. Treatment organizations tell us that junkies are victims of circumstance, not people who choose to abuse drugs. The people making these claims provide scientific studies as evidence. Because the idea is never challenged, we never questioned it to begin with and just accepted it into our worldview. I simply ask you to keep an open mind, because when you take a deeper look at the evidence, the idea of involuntary use starts to crumble.

## Brain scans

## Is addiction genetic?


## Scientific studies
- Meth or $20 study
- Alcohol button study / other NIMH studies

## Is treatment necessary?
- Moderation is possible, statistics

## Mental aspects
- Ritalin/meth
- Opiods
- Painkillers
- Zinberg study

## Why is the belief spread
- Addicts like the excuse
- More comforting for families
- Treatment centers / scientific institutions want people to sympathize
- Seems more accurate to outsiders

## Experience
- Our own experience supports: we want to use
