#  Addictive aspects {#why-addictive}
## Dopamine {#dopamine}
The main mechanism making social media addictive is dopamine. Dopamine is a chemical in the brain that is released when anticipating a reward. It reinforces and makes us repeat behaviors - if you eat a cookie (which releases dopamine) and find it pleasurable, you are likely to eat more. Sweet foods such as fruits were rare and valuable in prehistoric times, so our brains evolved to release dopamine in reaction to sugar, to encourage us to eat more of them. But in today's age, we have an unlimited supply of foods sweeter than anything natural, and many overconsume as a result. Social media also hijacks our natural rewards in the same way:

- We seek out and are rewarded for social connections. Social media keeps us constantly in the loop about friends and family and also lets us talk to millions of strangers across the globe. We also receive feedback from them in the form of "likes"/"dislikes". In fact, studies have shown more social media use to be connected with higher levels of loneliness time and time again.
- We are rewarded for finding information and novelty. When scrolling through social media posts or short videos, we are bombarding our brains with information and "new" things.
- Social media uses a variable reward scheme rather than a fixed reward scheme. This is the same principle that a slot machine uses. While you're scrolling through videos, whether you find a funny one and are entertained is random. Or when you make a post, you can't predict if it will blow up and get you many likes. Random rewards are much more addictive than predictable rewards. Imagine how less entertaining a slot machine would be if it simply rewarded you every 3rd spin instead of randomly.

USM use is the digital equivalent of junk food, releasing an amount of dopamine our brains were not equipped to handle on a daily basis. When an unnaturally high amount of dopamine is being released, the brain has a self-correcting mechanism to trim down the number of dopamine receptors.  The brain now receives less dopamine which brings rewards down from USM to normal levels. Unfortunately, it also decreases rewards from all other activities. Actions such as eating or talking to friends feel less satisfying while an increasing amount of USM use is needed to get that same "high". Without USM, the user starts to feel withdrawals. This process is called dopamine desensitization.

The physical effect of withdrawals is lowered dopamine levels in the brain. This results in a low mood, lack of pleasure from normal activities, boredom, and/or low motivation. If you watch YouTube for 5 hours, by the end you have no drive to accomplish anything and everything feels less enjoyable. USM addicts often suffer from anhedonia (loss of pleasure in normal activities) and find it difficult to muster the energy to work. 

Fortunately, the brain is able to recover from desensitization in a matter of weeks, with physical withdrawals diminishing then disappearing, if the source of unnaturally high dopamine (USM in our case) is removed.

## Intentional Design
All popular social media apps are free. They make income by showing advertisements to their users. These apps collect data on what you do in their apps, which posts you watch or like, what you search for, which communities you visit, etc. They do two things with this information:

- Feed it to their algorithms in order to determine which content to recommend to you. For example, as you use YouTube more, it will learn which videos you like watching, and the videos you get recommended will be more and more likely to draw your interest. The goal is to maximize the time you spend in their app to show you more advertisements.
- Serve you targeted ads based on your predicted demographics, location, and interests. With the personalized data they have, your attention becomes especially valuable to advertisers who are willing to pay more to show their ads to the exact type of customer they want.

Again, the more time you spend on their apps, the more data they collect and the more advertisements they can show you. Thus, they have an incentive to keep you on their apps for as much time as possible. Features like infinite scrolling and autoplay seek to make using their apps as frictionless as possible so you spend more time on them without realizing it. They also love to send you notifications, because each time you click on them and open the app is more time spent.

## Other factors
- *Availability*: For most of us, our phones are with us 24/7, with social media apps taking only a few seconds to access. This makes it easy to act on impulses and build habits of opening them. It also naturally fills up our downtime, such as if we're waiting at a bus stop.
- *Fear of missing out (FOMO)*: Humans hate being excluded socially. When putting down, for example, Facebook or Instagram, we worry about missing out on friends' activities. We also like being "in the loop" on current events and trends. It feels uncomfortable to not have access to this information if we are used to it.
