# The addiction trap
Even though users know all the trouble USM causes, the wasted time, loss of sleep, etc., they actually dread and fear the idea of quitting. They see USM as a crutch or vice which would cause them great pain to give up. Users are torn between wanting to keep using and wanting to quit. Remaining addicted looks like the lesser of two evils, so they choose to keep using rather than quit. This is the addiction trap. Try to understand this in your own experience use: you may recognize that quitting would be better and healthier for you (which I assume is true if you are reading this guide), but at the same time you WANT to pick up the phone to use USM. When you think of quitting, are you excited at the prospect of freedom, or get a feeling of anxiety?

From an outsider's perspective, it's easy to see that, for example, a heavy smoker really would be better off if he gave up smoking. After all, it causes numerous health issues, costs a lot of money, and for what benefit? The smoker, however, can't see it this way because he is inside the trap. USM addicts are likewise fooled by the trap into thinking that USM is a genuine benefit, or that they would suffer a great loss if they gave it up. (How exactly I will go over in Chapter \@ref(two-monsters)).

## The willpower method
As just stated, addicts both want to keep using and want to quit. The typical approach to quitting is to not address the desire to keep using and try to brute force it with willpower. If you are trying to resist your desire to use USM day in and day out with willpower alone, that is very difficult for a few reasons:

- You are constantly straining at the leash to fight against doing the very thing you want to do
- This stress is doubled without being able to turn to USM, which addicts are dependent on to deal with stress
- As you recover from addiction and withdrawal symptoms fade, the reasons you had for quitting start to disappear, and the want to use becomes stronger compared to the want to quit
- If you give in, it doesn't satisfy your cravings. Instead you want to use more and it is easy to fall back into your old ways

Clearly, this is a terrible way to go about things. There is a better way: if you are addicted to USM because you want to use it, all we need to do is convince you there is no benefit to it. Your desire to use USM will fade away and you will find it easy to quit.

