# How to quit
Earlier, I stated that addicts are people who are torn between wanting to quit and wanting to use. By now, you should realize there is no benefit to using USM. If you do, and you no longer want to keep using USM, you are no longer an addict. You are free.

Yes, it's that simple. There are no strategies or tricks required. Those are for addicts, which you no longer are. You simply decide you no longer want to use USM, deal with the physical withdrawal and little monster for a few weeks (nothing worse than what you feel every day), and you are done. 

Decide what parts of social media you'd like to keep in your life and what parts to cut out - what you consider USM versus a healthy use of social media. I recommend getting rid of all "recommended content" like YouTube recommended videos, Instagram reels or similar feeds, Facebook recommended posts, etc. There's really no point to them. What is left should be what enriches your life rather than making it emptier. Also consider what you get notifications from. Do you need to be notified every time a friend makes a post, or is it better to pick a time of the day to read through them all?

Once you've figured out what to get rid of, get rid of it completely. Delete your account, delete the app from your phone or computer, install a website blocker, make it as hard to access as possible. Any doubts you might have at this point are the work of the big monster panicking at the realization you might be serious about this. 

Be positive about your decision. You aren't losing anything, that's just what the little and big monsters want you to believe. You're making tremendous gains and losing an anchor around your neck.

## When should I quit?
Don't fall into the trap of thinking you'll quit "later". The trouble is that by the time later rolls around, it is "now" again and "later" is further away. The absolute best time to quit is right now, or as near to it as you manage. For example, if you use USM mainly when bored, you may want to stop on Monday so you'll be busy at the start. If you use it mainly in times of stress, picking the weekend may be better. If your desire to use USM is completely gone and you feel ready to quit, there's no point putting it off - rip off the bandage and quit.

## Cutting down
The big monster is deathly afraid of quitting. When it senses you are serious about changing, it offers a compromise: cutting down instead. Seemingly this gets you the best of both worlds. Your big monster is happy it gets to use USM, and you are happy because the downsides of using are smaller. Addicts who try to cut down realize you are actually getting the worst of both worlds: you continue to suffer the addiction, keeping the little monster alive the whole time, while not getting any of the benefits of quitting. The nature of any addiction is to use more and more. It's actually harder to cut down than to quit entirely.

If you are thinking of quitting completely but doing it by gradually cutting down, you will run into the same problems. Why go through all the trouble when you can just stop? The withdrawal symptoms are mild, not like those for alcohol or other serious drugs where stopping abruptly can be dangerous. 

## Relapse
The reason I instructed you to delete your accounts and apps is because in today's world, it's very difficult to get away from USM. Most of us are dependent on our phones or computers from which we can access USM in mere seconds barely consciously. The more obstacles you put in your way to accessing USM, the less likely it is you will use it again.

Another dangerous factor is "just one peek". If you are seriously tempted to take one peek, either you want to end your cravings or you still believe you are missing out on some pleasure or positive from USM. If it's the former, one peek won't end your cravings because USM causes cravings. As soon as you're done, the little monster will say "I want another". The only way to get rid of cravings is to stop using USM. If it's the latter, this is the work of the big monster. Something hasn't set in properly. Reread chapters \@ref(why-hard) and \@ref(benefits) to convince yourself there's no benefit to USM.

What if you do actually open USM again? If you are trying to quit with willpower, at this moment your will starts to run out, and you use it again and again until you are back to where you started. If you are quitting because you do not want to use USM anymore, using it doesn't change that fact. You used it probably because you didn't catch the big monster's thinking in the moment, or out of habit/unconsciously. Both issues will go away on their own as time goes on, but you can make the process faster by adding more obstacles in the way. Some people designate no-phone areas in their homes, such as forbidding phone use in their bedroom, while others pick a place as the only place they can use their phone. A common tip that works well is to ask yourself why you are picking up your phone whenever you do so. You can also reduce the amount of time you spend on screens in general, which has a number of benefits in addition to reducing USM use.

## What do I do now?
If you spent most of your free time with USM, quitting will leave something of a void - a void which the little monster would love to fill again with USM. What to do with all the free time you have now? What a wonderful problem to have! Spend it living your actual life - hang out with friends, call family, pick up some hobbies, attend social events, go out into nature, the list goes on. Reddit's r/nosurf community has compiled a list of activities [here](https://www.reddit.com/r/nosurf/wiki/activities/). There is a world beyond social media richer than anything you can see on a screen. 
