# Is addiction physical or mental? {#AP-mental}
It's obvious that there are both physical and mental/psychological aspects to addiction. There are physical symptoms such as withdrawals along with certain beliefs (such as seeing your addiction as a crutch) and emotions (such as fear of quitting) involved. The question I am interested in is this: which of these is the reason addicts find it so hard to stop?

Conventional wisdom says it's the physical reasons. I ask that you keep an open mind as I attempt to prove that it's actually the mental reasons which are keeping addicts in the addiction trap, by which I mean addicts keep using because in their minds the benefits outweigh the costs.

## Why does it matter?
Imagine that I wanted to start exercising at the gym for my health. At the same time, I find it hard to work up the motivation to actually go and work out for an hour, or keep a consistent schedule. In my mind, the benefits don't outweigh the costs. This is clearly a psychological problem. If you wanted to help me, you might tell me that "It's hard at first, but after some time it becomes fun" which reduces the cost in my mind. Or if I had a health scare, I would see more benefit in it and might be more motivated to go. Now imagine you said to me:

> The reason you can't go to the gym is because you are not physically in control. You got unlucky with your genetics and personality, so now whenever you try to go you will have massive difficulty which you need to fight with willpower. There is no cure, so you must take it one day at a time.

Supposing I believed you, my confidence would be destroyed! This is the issue with treating a psychological problem with a physical perspective. Since the root problem hasn't been solved, even if I do go to the gym, it will take all my willpower to keep going. What's more, if my mindset does change for whatever reason and the mental aspect is fixed, I will still have the idea in my mind that going to the gym will always be difficult and that it's because of some weakness within me.

Note that none of your arguments to me are really false either. In a sense, I am not in control because I intend to go to the gym but can't. Personality does play a role, in that some personalities would find it easy to go while mine doesn't, and personality is informed by genetics. I would indeed need willpower to keep going to the gym with my current state of mind, and there is no physical cure. The issue is that it is fundamentally very hard to motivate me to go to the gym by taking a physical perspective. It's like pushing on a door labeled "PULL".

On the flip side, if addiction really is a physical condition, we should treat it physically. If I had a heart disease and tried treating it psychologically, no matter what I do I will still have that disease. 

## Scientific Studies
Suppose I wanted to conduct a study to see if addicts are compelled to use physically, or they use because the benefits outweigh the costs. A simple way to do this would be to give addicts a choice between their drug and some amount of money.
