# The "benefits" of social media {#benefits}
At this point, even if you recognize that USM doesn't give you real pleasure, you may have in mind some other benefit it gives you. The supposed "benefits" generally are the same case as the illusion of pleasure, where USM causes the symptom that it temporarily relieves.

Another type of "benefit" is the excuse. I define an excuse as anything used to justify USM use but isn't the real reason they use USM. To use an analogy, smokers may say they smoke because they enjoy their particular brand of cigarettes. In reality if their preferred brand wasn't available, they would still smoke whatever was on hand. The most important reason we use USM is to feed the little monster, but users feel uncomfortable with that idea and find the excuses much easier to swallow. It doesn't help that everyone else is also using excuses and so we give them more validity in our minds. This process is only semi-conscious and often addicts don't know they're doing it, so whatever benefit you see in USM, try to interrogate it. Would you still use USM without that benefit? If so, it's an excuse.

::: {.rmdnote}
If you rationally weighed up the costs and benefits of using, the costs would win ten times over.
:::

## Relieving boredom
USM causes boredom itself. Remember that boredom is a symptom of dopamine withdrawal, and the high dopamine levels brought by USM cause said withdrawals. USM users are more bored in their day-to-day lives than non-users - It's only when they are using USM they can get rid of that boredom. For this reason, USM users find it harder to get work done or do chores.

Caveat: USM does relieve boredom in that if you are bored and you choose to use it, then you will be less bored while you are using it. But by using USM to kill time instead of anything fun, meaningful, or productive, you are wasting time and keeping the cycle of boredom going, since USM also causes boredom. And what do you get out of it? Once you're done you feel worse than when you started.

Many trying to quit USM report feeling something like a "void" in the first few days. If you have been overstimulating your brain with USM during every bit of downtime, it will take a little time to adapt to having that stimulation taken away.

## Relaxation
USM users state that it helps them relax or unwind. I will frame this in a different way: USM users find it difficult or impossible to relax while doing nothing, so they must have USM to relax. As long as you believe the big monster, the little monster's nagging makes it uncomfortable to be alone with your thoughts, so users can't relax as well as non-users in a situation such as sitting on a park bench on a nice day or putting your feet up after getting home from work.

## Concentration
Users know that USM can be extremely disruptive to focus. How often does just checking a notification turn into a wasted half hour while you should be doing work? At the same time, those who try to quit often have troubles concentrating on tasks. This is due to dopamine withdrawal causing boredom and low motivation and the distractions of the little and big monster. You get a craving and the big monster starts pestering you to let go of your work and use USM instead. Once you've defeated the big monster, your concentration restores to normal levels.

## Dealing with negative emotions
Stress, sadness, and anxiety are often caused by USM itself. There's the shame of having wasted hours, fear of missing out, the stress of deadlines after procrastinating with USM, etc. Even if we disregard that, is USM really a good way to deal with these emotions? It distracts you in the moment, but once you're done using, the emotions are still there. In fact, they've probably compounded.

## Social connections
Remember from Chapter \@ref(dopamine) that our brain rewards us for building social connections. Social media games this by providing us many more social connections than in the real world at the cost of not being as fulfilling. Does it really matter how many complete strangers from across the country or friends of friends of friends "like" your post or comment? No, the point is to feed your little monster.

I will throw personal social media a bone and say it CAN be used for authentic social connection if used very carefully. I don't think there's anything wrong with posting family pictures for close friends to see. Lots of people who text or call their friends do it on social media apps, so if you use those apps just to text or call them, I would say it's a good use. The problem is that social media can replace real-world interactions. The benefit from browsing friends' posts is nowhere near that of having a cup of coffee with them. Plus, the more time you spend on USM in general, the less time that leaves for real-world interactions.

## Entertainment
This mainly applies to impersonal social media. The idea that USM is more entertaining than, say, watching a movie is essentially a symptom of withdrawals. Heavy users don't get as much enjoyment out of watching a movie because of dopamine withdrawal. They are physically more bored and have a restless feeling, like they'd love to be using USM instead. USM may be entertaining at first, but as your tolerance increases it becomes less and less so. 

Perhaps you can point to specific YouTube channels or comics you follow as real entertainment. Perhaps, but then why scroll through infinite feeds of recommended posts on these apps? 

## Information
Social media does have plenty of useful information, but this is not by itself a reason to use USM since said information is almost always found easier and faster elsewhere, without any of the downsides or major distraction provided by USM. 

Some enjoy learning fun facts or trivia through their USM feeds. In the same vein as entertainment, a long article or book can't compete with the dopamine release from USM in terms of interest. The article is plenty interesting in the eyes of a non-user.

## Keeping up
On the personal side, there is keeping up with friends' and colleagues' social media posts. Maybe you can argue that it's a benefit to be aware of, for example, events that happen in your city which are posted on social media, which I would agree with, but the desire to keep up can quickly become the fear of missing out (FOMO). This is provoked by USM - those who don't use it don't need to check it daily to not feel like they're missing out. A modern proverb goes, "After one day without social media, I feel like I missed everything; after one month, I feel like I missed nothing". Examine whether you are actually getting useful information and keeping in touch with loved ones or just keeping up for the sake of keeping up.

On the impersonal side, there is keeping up with news and politics. If you're looking at reputable news organizations that happen to have pages on social media, fair enough. But getting information from regular users is risky at best. Without any regulation, misinformation is abundant on social media. A study from *Science* indicates that fake news spreads 6 times faster than real news because it is more emotionally charged and more attention-grabbing^[https://science.sciencemag.org/content/359/6380/1146.full]. An Oxford University study of 22 million political tweets in 2017 found users shared more "misinformation, polarizing, and conspiratorial content” than actual news^[https://www.researchgate.net/publication/323142063_Social_Media_News_and_Political_Information_during_the_US_Election_Was_Polarizing_Content_Concentrated_in_Swing_States]. Don't think it's so easy to tell which is which - sure, if it seems outrageously wrong you can tell, but what about misinformation which you agree with? When you read a fact or statistic that confirms what you already thought, do you go out of your way to check it?

If you think social media is good for political content, here is an experiment you can try. Seek out a political group on social media that opposes your beliefs. If you read through them, you will probably notice lots of misinformation and nonsensical points. People tend to believe almost anything if it's repeated over and over among people they know, like, or see common ground with. Over time, this creates an "echo chamber", where false facts are never challenged and keep growing. What is happening to these people is also happening to you, it doesn't matter how "rational" you think you are. All users on social media are exposed to staggering amounts of fake news, and since nobody fact-checks every single thing they read this inevitably turns into false beliefs. Garbage in, garbage out.  Here's one more study: Researchers from Carnegie Mellon judged 45% of tweets about the coronavirus in early 2020 to be likely written by bots contributing to over 100 false narratives.^[https://www.kpbs.org/news/2020/may/20/researchers-nearly-half-of-accounts-tweeting/]

::: {.rmdnote}
Each side thinks they are perfectly logical and obviously correct while the other side is crazy.
:::

## The benefits of quitting
Addicts dealing with the big monster despair at the thought of quitting. I would like to emphasize the benefits of quitting in order to cement the idea that quitting is the happier option for you, compared to staying addicted to USM. Don't skim through this list! Read each item carefully and envision the benefit of each one.

- No cravings from the little monster
- Reclaiming all the time you spend on USM
- Not being distracted by USM while trying to work, or procrastinating with USM
- Better attention span
- No dopamine withdrawal (better mood, less boredom, more motivation)
- Not losing sleep late at night to USM
- No shame from being addicted
- No fear of being hooked for life
- Being able to enjoy the moment without USM at hand
- No longer comparing yourself to strangers online
- Less tiredness
