# How to quit
Earlier, I stated that addicts are people who are torn between wanting to quit and wanting to use. The central message of this guide so far has been: There is virtually no benefit from using USM. If you have properly absorbed this, and no longer want to use USM, you are no longer an addict. You are free.

::: {.rmdnote data-latex=""}
If you fully understand USM has no benefit, you will probably still have cravings, but you shouldn't fear them. You should also recognize using USM would only keep them going.
:::

Yes, it's that simple. There are no strategies or tricks required. Those are for addicts, which you no longer are. You simply decide you no longer want to use USM, deal with the physical withdrawal for a few weeks (nothing worse than what you feel every day), and you are done. For convenience, I've organized the process of quitting into steps:

**1. Get rid of doubts**

Examine what benefits you still see in USM. Look at them critically: most of them will either be false benefits that only relieve the symptoms USM causes, or excuses. Remember, if you weighed up the costs and benefits, the benefits of quitting would win ten times over. If you can do this, there's no reason to fear quitting - it may have been hard before, but now that you've solved the puzzle it'll be no trouble at all.

::: {.rmdnote data-latex=""}
If you could go back to before you began using USM and had the choice whether to do it or not, which would you choose? You have that choice now.
:::

**2. Decide what to cut**

Decide what parts of social media you'd like to keep in your life and what parts to cut out - what you consider USM versus a healthy use of social media. I recommend getting rid of all impersonal social media like YouTube recommended videos, Instagram reels or similar feeds, Facebook recommended posts, Reddit, etc. There's really no point to them. What is left should be uses of personal social media that enrich your life rather than make it emptier. Also consider what you get notifications from. Do you need to be notified every time a friend makes a post, or is it better to pick a time of the day to read through them all?

Even healthy uses of social media can be problematic because they put you closer to USM. The more social media you can cut and the more distance you keep from USM, the less risk of using again and more peace of mind you have.

**3. Commit to quitting**

Make a serious commitment to quit USM. Don't go back on it and never doubt it.

**4. Add friction**

Whatever you've decided to get rid of, get rid of it completely. Delete your account, delete the app from your phone or computer, install a website blocker (see Appendix \@ref(AP-soft)), make it as hard to access as possible.

**5. Get on with your life**

If you spent most of your free time with USM, quitting will leave something of a void, a feeling of "well... now what?". What to do with all the free time you have now? What a wonderful problem to have! Spend it living your actual life - hang out with friends, call family, pick up some hobbies, attend social events, go out into nature. Reddit's r/nosurf community has compiled a list of activities [here](https://www.reddit.com/r/nosurf/wiki/activities/). 

The important thing is not to mope about your decision to quit or obsess over USM. When you think of USM, look on the bright side. Remind yourself of all that you're gaining and get on with whatever you want to do. Living is more enjoyable without having to worry about that anchor around your neck.

## Can I still use social media for...
Even if you are committed to quitting USM, you may have legitimate reasons to use social media, or cases you think might blur the line between USM and healthy use. One question you can ask yourself is "Is this the *best* way to accomplish this task?" For example, if you usually scroll through comedy clips on social media to laugh, you may find it better to instead watch a sitcom or stand-up show, which comes with much less downside than USM. If it seems like a poor replacement, remember that since USM is addictive, everything else seems less interesting, informative, or funny in comparison, at least while you're still addicted. 

Even if you use social media websites, you can strictly limit how and when you use them. If you want to keep up with friends' posts, you can decide to check your feed once a week at a specific time. Limiting social media use in this way reduces its addictive potential if you can stick to the schedule. The danger is that by using social media sites, you are putting yourself very close to USM features, increasing the risk you'll click on them on a whim or through habit. For this reason, it's better to cut social media websites out as much as you can. Another strategy is to use tools such as browser extensions (see Appendix \@ref(AP-soft)) to specifically block USM features of apps to reduce the danger.

I was tempted to say you should quit using social media in all forms. Unless it's necessary for your job, if you were committed to doing so, you would probably find that it's not actually needed for any reason. Keeping in touch with friends is nice, but you can do that by meeting up in person or texting or calling them on other platforms. This would be the best advice I could give, but I suspected if I said this, some people would ignore it, continue to use social media without regard for the risk, and eventually fall back into USM addiction.

If you're still not sure about cutting out a use of social media, you can always try cutting it for a week or two to get a better idea of if you can do without it. 

## When should I quit?
Don't fall into the trap of thinking you'll quit "later". The trouble is that by the time later rolls around, it is "now" again and "later" is further away. The absolute best time to quit is right now, or as near to it as you manage. For example, if you use USM mainly when bored, you may want to stop on Monday so you'll be busy at the start. If you use it mainly in times of stress, picking the weekend may be better. If your desire to use USM is completely gone and you feel ready to quit, there's no point putting it off - rip off the bandage and quit.

## Relapse
The reason I instructed you to delete your accounts and apps is because in today's world, it's very difficult to get away from USM. Most of us are dependent on our phones or computers from which we can access USM in mere seconds barely consciously. The more obstacles you put in your way to accessing USM, the less likely it is you will use it again.

Another dangerous factor is "just one peek". If you are seriously tempted to take one peek, either you want to end your cravings or you still believe you are missing out on some pleasure or positive from USM. If it's the former, one peek won't end your cravings because USM causes cravings. As soon as you're done, part of you will think "I want another". The only way to get rid of cravings is to stop using USM. If it's the latter, something hasn't set in properly. Reread chapters \@ref(the-trap) and \@ref(benefits) to convince yourself there's no benefit to USM.

::: {.rmdcaution data-latex=""}
There is no such thing as "just one peek". All USM addictions started with just one peek. Even if you feel in control, it can quickly spiral back down.
:::

What if you do actually open USM again? If you are trying to quit with willpower, at this moment your will starts to run out, and you use it again and again until you are back to where you started. If you are quitting because you do not want to use USM anymore, using it doesn't change that fact. You used it probably because you didn't catch your misguided thinking in the moment, or out of habit/unconsciously. Both issues will go away on their own as time goes on, but you can make the process faster by adding more obstacles in the way. Some people designate no-phone areas in their homes, such as forbidding phone use in their bedroom, while others pick a place as the only place they can use their phone. A common tip that works well is to ask yourself why you are picking up your phone whenever you do so. You can also reduce the amount of time you spend on screens in general, which has a number of benefits in addition to reducing USM use.
