# Difficulties in quitting
How do you quit a job? It's sort of a silly question. You say "I quit" and you never go back to the job again. With USM, it's easy to say "I quit" but the trouble lies in making sure you don't return.

## The willpower method
As stated previously, addicts both want to keep using and want to quit. The typical approach to quitting is to not address the desire to keep using and try to brute force it with willpower. If you are trying to resist your desire to use USM day in and day out with willpower alone, that is very difficult for a few reasons:

- You are constantly straining at the leash to fight against doing the very thing you want to do
- This stress is doubled without being able to turn to USM, which addicts are dependent on to deal with stress
- As you recover from addiction and withdrawal symptoms fade, the reasons you had for quitting start to disappear, and the desire to quit becomes weaker
- If you give in, it doesn't satisfy your cravings. Instead you want to use more and it is easy to fall back into your old ways
- USM appears more precious, like dieting makes unhealthy food more tempting

The hope is that if you can go long enough without using USM, the desire to use it will go away. This does work for many people, it sinks in that life is better without USM and the former addict can live freely. But overall, the rate of failure is high for the reasons I listed above. Even if one succeeds, since they still believe they are being deprived, they might be pining to use USM long after they kicked the physical addiction.

::: {.rmdnote data-latex=""}
Quitting with willpower is hard because you are trying to not do something you desparately want to do.
:::

## The fear of quitting
Have you ever felt a twinge of panic when you opened up a social media site to find the servers were down, or found your internet wasn't working? Non-addicts don't feel that fear. USM users are afraid to quit because they believe they are losing a crutch or genuine pleasure (believing the illusion of pleasure). They fear that the emptiness and boredom they feel when not using USM will be with them forever (not understanding dopamine desensitization). They despair at the thought of never getting the pleasure of using USM again (the illusion of pleasure). By now you should realize that all of these feelings are irrational. There is also the fear of withdrawals and cravings which I have yet to address.

### Withdrawals and cravings
We already went over the physical effects of dopamine withdrawal: low mood, boredom, a feeling of something being missing, etc. These symptoms are experienced by USM users every day when they put down their phone, and are easily bearable on their own even for extended periods of time. The trouble with withdrawals is not the physical aspects, but the psychological ones. While feeling the symptoms, you think "If only I could use USM now, it would solve all my problems". The problems were caused by USM and all you need to do to get over them permanently is to bear temporary discomfort. 

During attempts to quit, you will occasionally get the sudden impulsive thought that you want to use USM - a craving. This tends to happen in situations where you normally use USM, such as if you've made a habit of using it in bed before sleep, but can happen at any time. If you're trying to quit with willpower, this is where your will is truly tested. You feel like you'll never be satisfied without USM. You tell yourself just this once won't hurt. You think that you picked the wrong time to quit, or maybe you can just cut down instead. You doubt if the suffering you're going through is worth it and that maybe it's better to be an addict. 

Again, the thought by itself is practically a non-issue. All the thoughts that come after, the strong urges to use, stress and anxiety, etc. come from the belief that you're giving up a real pleasure and the fear of having to live without USM. Once you realize these are irrational. cravings lose their power. Humans have enough self-awareness to be able to ignore cravings if they truly believe it's for the better. By themselves, cravings are little more than intrusive thoughts - annoying, but ultimately they have no power over you. 

::: {.rmdnote data-latex=""}
The pain from withdrawals and cravings is almost entirely mental.
:::

You may still pull out your phone to open USM as habit, or think without realizing "I should open (your USM app of choice)". Like a spinning wheel, these habits will continue for some time, but if you don't give in to them or mope about them the wheel will eventually grind to a halt.

Let me clearly state that there is nothing to be afraid of in quitting at all, nor is it difficult, once you have removed the desire to use USM. Anyone who thinks it difficult to quit, or fears life after quitting, still does not realize USM's only benefit is the removal of withdrawals caused by USM. Going back to the job example, if you worked a job you loathed and truly never wanted to work at again, would it be difficult to say "I quit" and never go back to that job? Of course not. It would only be a difficult process if you were torn between leaving and staying.

## Cutting down
If you still believe there is some pleasure to USM or fear quitting, you might think about cutting down instead of quitting. Seemingly this gets you the best of both worlds. You get to use USM without the harsh downsides of being addicted. Addicts who try to cut down realize you are actually getting the worst of both worlds: you continue to suffer the addiction, keeping the withdrawals and cravings the whole time, while not getting any of the benefits of quitting. The nature of any addiction is to use more and more. For these reasons, it's actually harder to cut down than to quit entirely.

If you are thinking of quitting completely but doing it by gradually cutting down, you will run into the same problems. Why go through all the trouble? The withdrawal symptoms are mild, not like those for alcohol or other serious drugs where stopping abruptly can be dangerous. 
