# The addiction trap {#the-trap}
Even though users know all the trouble USM causes, the wasted time, loss of sleep, etc., they actually dread and fear the idea of quitting. They see USM as a crutch or vice which would cause them great pain to give up. Users are torn between wanting to keep using and wanting to quit. Remaining addicted looks like the lesser of two evils, so they choose to keep using rather than quit. This is the addiction trap. Try to understand this in your own experience of USM use: you may recognize that quitting would be better and healthier for you (which I assume is true if you are reading this guide), but at the same time you WANT to pick up the phone to use USM. When you think of quitting, are you excited at the prospect of freedom, or get a feeling of anxiety?

::: {.rmdnote data-latex=""}
Addiction is suffering, but to addicts it looks like the lesser of two evils compared to quitting.
:::

From an outsider's perspective, it's easy to see that, for example, a heavy smoker really would be better off if he gave up smoking. After all, it causes numerous health issues, costs a lot of money, and for what benefit? The smoker, however, can't see it this way because he is inside the trap. USM addicts are likewise fooled by the trap into thinking that USM is a genuine pleasure or benefit, or that they would suffer a great loss if they gave it up.

Some readers might disagree: what about all the terrible physical symptoms of addiction? The cravings, the withdrawals, the habits? These no doubt exist, but they are not the reason addicts keep using. USM addicts are perfectly capable of bearing them throughout the day every time they put down USM. Think of it this way: would you be willing to go through the flu if at the end you were completely cured of your addiction? If so, since the flu is worse than the physical effect of quitting, we have to conclude you won't quit for mental reasons.

<!---
If you still have doubts, read Appendix \@ref(AP-mental) and continue with the rest of the book when you're done.
--->

## The illusion of pleasure
Remember that all addicts are pulled in two directions, wanting to quit and wanting to use. Why do we want to use, despite knowing how much the costs outweigh the benefits? It's because of the illusion of pleasure. In short, we think that USM is pleasurable, we see it as a vice, or we fear being deprived of all the enjoyment of USM. This belief is the true cause of your addiction, compared to withdrawals and cravings which are a minor nuisance in comparison. The belief that there is pleasure in USM is completely untrue. I don't mean that the pleasure is outweighed by the costs. I mean *there is no pleasure in USM at all*.

Remember that as you use USM more and more, dopamine desensitization occurs in the brain. You go through your life with lowered dopamine levels experiencing withdrawal most of the time and USM is the only thing which will bring you back to normal levels. Non-users don't get withdrawals, and the relief you get from using USM is what they feel all the time. In other words, you use USM to feel like someone who doesn't. Clearly you would have been better off if you hadn't become hooked in the first place. All you need to do is to stop using USM and your dopamine levels will return to normal.

You may be thinking "I know that already" but it probably hasn't truly sunk in. The problem is that the facts don't fit in with a user's experience. It is when you are using USM that you feel normal, and when you are not using, you suffer from withdrawal. When you feel low and empty, as soon as you pick up USM, your problem is cured. Your brain makes the obvious connection: using social media makes you feel better, not using it makes you feel bad, therefore it must be a good thing. This is the opposite of the truth - whenever you stop USM you feel bored, or empty, or depressed, but this is caused itself by using USM. Addicts think that their problems will be solved by the next hit of their drug, but in reality they were caused by the previous hit - an endless cycle until you break out.

::: {.rmdnote}
The pleasure of USM is only a relief from the withdrawal that USM causes.
:::

We don't see it this way because the process of building tolerance to dopamine is slow and gradual. If the instant you used USM for the first time, you became hooked, becoming restless without it and needing to use it for hours to get through the day, it would quickly register that USM was the problem. In reality, withdrawals are slight as we begin to use, so we don't blame USM. By the time we realize we need to cut down, USM has cemented its place in our mind as something to reach for when we need a boost, to relax, or whenever we're bored and it doesn't occur to us the problems it fixes are the very ones it causes.

To use an analogy, it's like wearing tight shoes all day for the "pleasure" of taking them off. There is real relief, but only from the pain caused by the shoes themselves. USM only seems different because instead of USM causing pain while you are using it, it causes pain while you are not using it. The relief comes when you are using USM, and stopping is when withdrawal starts. But the situations are exactly the same otherwise.

Another contributor to the illusion is other people. Since all other USM addicts are also in the trap, they also fall for the illusion and report that they want to quit USM, but it's just *so enjoyable*. This has a profound impact on your subconscious when repeated. The effect is to accept without taking for granted the pleasure of USM. Whenever you hear anything to this effect, remember they've just fallen for the trap like you have.

You may have heard of smokers who have quit for years, then pick up one cigarette and are hooked again. You may also have heard of alcoholics who quit drinking but have been miserable without alcohol since then. They were cured of any physical symptoms long ago, but eventually chose the pleasure of the drug - a pleasure that doesn't actually exist. Setting off the chain reaction of withdrawal, they fell back into the trap of addiction.
