# The two monsters {#two-monsters}

## The little monster
In Chapter \@ref(dopamine) I went over dopamine. The main reason we use USM is to end dopamine withdrawal and feed the "little monster". The little monster awakens when we go through dopamine withdrawal. Whenever you have free time, it feels like something is missing. You feel empty or restless - this is the little monster begging to be fed. If we give in to it, we are satisfied momentarily, but once we put down USM, dopamine levels start to decrease, starting the cycle over again.

::: {.rmdnote}
Dopamine withdrawal is caused by USM use, not relieved by it. No non-user ever went through USM withdrawal.
:::

If you abstain from USM for long enough, as your dopamine baseline returns to normal, the little monster will grow weaker and weaker before eventually dying out. The empty feeling disappears along with the other symptoms of withdrawals (low mood, lack of motivation and pleasure).

By itself, the little monster is a minor threat and if this was all there was to it, quitting would be easy.

## The big monster
Much more dangerous than the little monster is the big monster. Remember that all addicts are pulled in two directions, wanting to quit and wanting to use. The big monster is the part of you that wants to use. It comes from the (false) belief that USM gives you genuine pleasure or benefit. Once you understand it, there is no reason to want to use USM anymore.

You may have heard of smokers who have quit for years, then pick up one cigarette and are hooked again. You may also have heard of alcoholics who quit drinking but have been miserable without alcohol since then. They defeated the little monster long ago, but failing to address the big monster, they eventually chose the pleasure of the drug - a pleasure that doesn't actually exist. Setting off the little monster, they fell back into the trap of addiction.

### The illusion of pleasure
I mentioned that USM users are fooled into thinking thinking that there is a genuine pleasure to USM. This can be attributed to the dopamine release that USM causes. Remember that as you use more and more, dopamine desensitization occurs in the brain. You go through your life with lowered dopamine levels experiencing withdrawal most of the time and need to use USM to return to normal levels. Non-users don't get withdrawals, and the relief you get from using USM is what they feel all the time. In other words, you use USM to feel like someone who doesn't. Clearly you would have been better off if you hadn't become hooked in the first place. All you need to do is to stop using USM and your dopamine levels will return to normal.

You may be thinking "I know that already" but it probably hasn't truly sunk in. The problem is that the facts don't fit in with a user's experience. It is when you are using USM that you feel normal, and when you are not using, you suffer from withdrawal. When you feel low and empty, as soon as you pick up USM, your problem is cured. Your brain makes the obvious connection: using social media makes you feel better, not using it makes you feel bad, therefore it must be a good thing. This is the opposite of the truth - whenever you stop USM you feel bored, or empty, or depressed, but this is caused itself by using USM. Addicts think that their problems will be solved by the next hit of their drug, but in reality they were caused by the previous hit - an endless cycle until you break out.

::: {.rmdnote}
Using USM is like wearing tight shoes all day to get the "pleasure" of taking them off. Taking the shoes off is a relief, but only from the pain it causes.
:::

Think of the absolute misery heroin addicts go through when they are deprived of their drug. Now think of the utter joy they get when they are finally able to stick a needle in their veins and end their cravings. Non-heroin addicts don't get that feeling of joy - it's caused by the little monster. We don't see it this way because the process of building tolerance to dopamine is slow and gradual. If the instant you used USM for the first time, you became hooked, becoming restless without it and needing to use it for hours to get through the day, it would quickly register that USM was the problem. In reality, withdrawals are slight as we begin to use, so we don't blame USM. By the time we realize we need to cut down, USM has cemented its place in our mind as something to reach for when we need a boost, to relax, or whenever we're bored and it doesn't occur to us the problems it fixes are the very ones it causes.

Another contributor to the illusion is other people. Since all other USM addicts are also in the trap, they also fall for the illusion and report that they want to quit USM, but it's just *so enjoyable*. This has a profound impact on your subconscious when repeated. The effect is to accept without taking for granted the pleasure of USM. Whenever you hear anything to this effect, take note the "enjoyment" is just the removal of the withdrawal.
